site_name: HP Data Quality ETL
repo_url: https://github.com/topcoderinc/HP-Data-Quality-ETL-project
pages:
    - Project Docs:
      - 'This Project introduction': index.md
      - Component Details: component_details.md
      - Architecure Docs:
        - Application Design Spec: architecture/Application_Design_Specification.md
      - Wireframes: webDesign/wireframeIframe.md
      - Storyboards: webDesign/storyboardIframe.md  
    - Topcoder Docs:
       - 'Copilot Responsibilities': topcoder/copilotsResponsiblites.md
       - code:
          - 'Fixing Bugs from github': topcoder/fixingBugs.md
          - 'Ragnar: Git Process': topcoder/RagnarGit.md
       - tcprojWrapper: topcoder/tcProjWrapper.md
theme_dir: cinder/site
